version: "3.3"

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # install requirements.txt

    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://hello_fastapi_postgres:hello_fastapi_postgres@db/notes_db
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_fastapi_postgres
      - POSTGRES_PASSWORD=hello_fastapi_postgres
      - POSTGRES_DB=notes_db

volumes:
  postgres_data:

networks:
  default:
      name: notes_fastapi